// This is an autogenerated file from Firebase Studio.
'use server';

/**
 * @fileOverview Categorizes unstructured UPI transaction data using AI to identify and reconcile transactions.
 *
 * - categorizeUpiTransaction - A function that categorizes a UPI transaction.
 * - CategorizeUpiTransactionInput - The input type for the categorizeUpiTransaction function.
 * - CategorizeUpiTransactionOutput - The return type for the categorizeUpiTransaction function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const CategorizeUpiTransactionInputSchema = z.object({
  transactionData: z
    .string()
    .describe('The unstructured UPI transaction data to categorize.'),
});
export type CategorizeUpiTransactionInput = z.infer<
  typeof CategorizeUpiTransactionInputSchema
>;

const CategorizeUpiTransactionOutputSchema = z.object({
  category: z.string().describe('The category of the UPI transaction.'),
  description: z.string().describe('A description of the transaction.'),
  isReconciled: z
    .boolean()
    .describe('Whether the transaction has been reconciled.'),
  reconciliationNotes: z
    .string()
    .describe('Notes on the reconciliation of the transaction.')
    .optional(),
});
export type CategorizeUpiTransactionOutput = z.infer<
  typeof CategorizeUpiTransactionOutputSchema
>;

export async function categorizeUpiTransaction(
  input: CategorizeUpiTransactionInput
): Promise<CategorizeUpiTransactionOutput> {
  return categorizeUpiTransactionFlow(input);
}

const categorizeUpiTransactionPrompt = ai.definePrompt({
  name: 'categorizeUpiTransactionPrompt',
  input: {schema: CategorizeUpiTransactionInputSchema},
  output: {schema: CategorizeUpiTransactionOutputSchema},
  prompt: `You are an AI assistant that categorizes UPI transactions.

  Analyze the following transaction data and determine the category, description, and whether it has been reconciled.
  If it has not been reconciled, provide notes on the reconciliation.

  Transaction Data: {{{transactionData}}}
  `,
});

const categorizeUpiTransactionFlow = ai.defineFlow(
  {
    name: 'categorizeUpiTransactionFlow',
    inputSchema: CategorizeUpiTransactionInputSchema,
    outputSchema: CategorizeUpiTransactionOutputSchema,
  },
  async input => {
    const {output} = await categorizeUpiTransactionPrompt(input);
    return output!;
  }
);
